# Generated by Django 2.1.7 on 2019-04-14 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=60)),
                ('lastname', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ArtisteType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artistId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PID.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='ArtisteTypeShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artisteTypeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PID.ArtisteType')),
            ],
        ),
        migrations.CreateModel(
            name='Localitie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=60)),
                ('website', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=30)),
                ('localityId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PID.Localitie')),
            ],
        ),
        migrations.CreateModel(
            name='Representation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationId', models.ManyToManyField(blank=True, related_name='representation', to='PID.Location')),
            ],
        ),
        migrations.CreateModel(
            name='RepresentationUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('places', models.IntegerField()),
                ('representationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PID.Representation')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('posteUrl', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bookable', models.SmallIntegerField()),
                ('locationId', models.ManyToManyField(blank=True, related_name='show', to='PID.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=60)),
                ('lastname', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=100)),
                ('langue', models.CharField(max_length=2)),
                ('roleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PID.Role')),
            ],
        ),
        migrations.AddField(
            model_name='representationuser',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PID.User'),
        ),
        migrations.AddField(
            model_name='representation',
            name='showId',
            field=models.ManyToManyField(blank=True, related_name='representation', to='PID.Show'),
        ),
        migrations.AddField(
            model_name='artistetypeshow',
            name='showId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PID.Show'),
        ),
        migrations.AddField(
            model_name='artistetype',
            name='typeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PID.Type'),
        ),
    ]
