# Generated by Django 2.1.7 on 2019-09-05 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=60)),
                ('lastname', models.CharField(max_length=60)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PID.Agency')),
            ],
        ),
        migrations.CreateModel(
            name='ArtisteType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artistId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PID.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='ArtisteTypeShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artisteTypeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PID.ArtisteType')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Localitie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=60)),
                ('website', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=30)),
                ('localityId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PID.Localitie')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=60)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Representation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationId', models.ManyToManyField(blank=True, related_name='representation', to='PID.Location')),
            ],
        ),
        migrations.CreateModel(
            name='RepresentationUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('places', models.IntegerField()),
                ('representationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PID.Representation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('posterUrl', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bookable', models.SmallIntegerField()),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PID.Category')),
                ('location_id', models.ManyToManyField(blank=True, related_name='show', to='PID.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='representation',
            name='showId',
            field=models.ManyToManyField(blank=True, related_name='representation', to='PID.Show'),
        ),
        migrations.AddField(
            model_name='artistetypeshow',
            name='showId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PID.Show'),
        ),
        migrations.AddField(
            model_name='artistetype',
            name='typeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PID.Type'),
        ),
    ]
