# Generated by Django 2.1.7 on 2019-09-05 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PID', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='agency',
        ),
        migrations.DeleteModel(
            name='Agency',
        ),
    ]
