# Generated by Django 2.1.7 on 2019-03-21 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PID', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='place',
        ),
    ]
