# Generated by Django 2.1.7 on 2019-05-05 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PID', '0002_auto_20190505_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='role_id',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='representationuser',
            old_name='userId',
            new_name='user',
        ),
    ]
