# Generated by Django 2.1.7 on 2019-05-05 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PID', '0003_auto_20190505_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
