# Generated by Django 2.1.7 on 2019-06-13 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PID', '0004_auto_20190505_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='show',
            name='category_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='PID.Category'),
        ),
    ]
