# Generated by Django 2.1.7 on 2019-08-03 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PID', '0005_auto_20190613_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='locationId',
            new_name='location_id',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='posteUrl',
            new_name='posterUrl',
        ),
        migrations.RemoveField(
            model_name='show',
            name='category_id',
        ),
        migrations.AddField(
            model_name='show',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PID.Category'),
        ),
    ]
